apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app-server
  name: app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/frontend: "true"
        io.kompose.service: app-server
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/testdata
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: spring.jpa.hibernate.ddl-auto
              value: create
            - name: spring.jpa.properties.hibernate.dialect
              value: org.hibernate.dialect.MySQL5InnoDBDialect
          image: docker.io/aminemeeed/cabinet
          name: app-server
          ports:
            - containerPort: 8091
          resources: {}
      restartPolicy: Always
status: {}
